title: NObao - Программирование и верстка
name: NObao
description: Процесс моего обучения программированию на JavaScript, верстке, а также новости по данной тематике

themecolor: '#202225'
imagehome: img/nobao.jpg
url: 'https://nobao.ru'
baseurl: '/' # the subpath of your site, e.g. /blog

plugins: [jekyll-paginate-v2]
category_dir: blog
pagination:
  enabled: true
  per_page: 9
  title: ':title - Страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'package-lock.json', 'js/common.js', 'npm-debug.log', '**/Thumbs.db', 'libs', 'sass', '**/*.DS_Store']

soc:
  <li><a href="https://vk.com/nobao"><i class="fa fa-vk"></i></a></li>
  <li><a href="https://www.facebook.com/NOBAO-113798983364599/"><i class="fa fa-facebook"></i></a></li>
  <li><a href="https://www.instagram.com/nobao_code/"><i class="fa fa-instagram"></i></a></li>
  <li><a href="https://twitter.com/nobao_code"><i class="fa fa-twitter"></i></a></li>
  <li><a href="#"><i class="fa fa-rss"></i></a></li>

copyright: 'Копирование контента и размещение на других сайтах запрещено.'